version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx:1.0.0
    ports:
      - "82:80" # Cambia esto si necesitas otro puerto
  #   depends_on:
  #      - andon_report
    volumes:
      - /home/maganaj/volumes/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - report_network

networks:
  report_network:
    external: true